[gcp_service_account]
type = "service_account"
project_id = "coherent-medium-474812-q4"
private_key_id = "c3d70b35c8c3ace002e9cbe5465d64e30830a054"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCxyn7nDrG8pRGf
UwAydmRc8IbDbGRoLw+czT2cUISM2sab9EtAOGARRsCWKgOXW4GjjzvSjn/oxjIn
1zTitKJ2Gdr7mMRlR2rYYpplSGDoBgHhAqxgPMyxd4ZXmnFq8ZqxOVIg3pXChmAw
8ypHm5r+ZLGQGL/If2XjnW0RED6ywC7HQESq/z93uwOtY2a1d2zmBDmhD1qqZwc6
2WKM8f8eqv0R4K9HPMonsUpiI/T4+rt3AGZ+23OVXJtv7o5VqpXoDkfzP8xK5A5M
9P8w4NEZDxqDn8BIz9SUePn69pg/0/uIpybpJ6R6D7T3oUKFi1ixQ/W+ilD44ed9
9pQd+CEhAgMBAAECggEAB+EiE6pujR5BtC5xBUuC8i2Ew3dz0bw4NGpSLzHQVg/C
GppOlXeKJmnc0irlgtk+2xlXfOLs30udYG+ku+Fmi9Zkgp8IITbzkMh58EAvb0kI
30iHjDJVng3eidZh7Wvsv6r7LVLAD2F2NOUp/Ad07I5Y4jp+kWu3/8jz0vxF0xUn
cy1Vzi9swBrt3AslhUwuBlp9jVYBO0euSOKJi7rsl3Kek0GEiLdv358LAkIrvpgX
X4Bh3Z+zir7pr+4HZZM4vXfIT9upwNpbA6ZTZGNJ3rO0fCOVocdlC31npjekotf4
UxDnARWHUivBaAY6/UEhtUuoi8NUehqzBhQc+izYGQKBgQDagy6+q7656NcF9Arx
6jnSWaEroqbIaKQ/dBasN5wQaXviszzaQ6uxj34s7LvPNTL1Keej5SIo4m+wk0d9
nG6jcSfX/IRX4t7nLtdR5PotqgIufo2hycG8GVH9vSu8mbGZwSlkwZIvUwqEVUZ7
ZuakQbqzsnDFxtVHLCcmNLHbVQKBgQDQSt/FPC4P7xQeP+7ytJ2DwvGVepdpSonW
ObWse3Vep9s8lCHYbkL/NJDW67e8orLYL2pYN0+CoLqNRaa6YdV1KHRRDwRKtxJA
z0ojsUn+Fe9sRqPglzPsPtNUPMwPkGYO1lKbrt/a+sSIe/U9iTFgzFB3YNtAl3AU
dmA8qP4mnQKBgASmtDEE0Nt+NE2BI1aA6NgsZjzainhLmetr2iuyR1UmGaf6rrnq
pNXzuvjT1S+U70++o5qefvqlz0DP8b6fvM8n0nRLgLmqL5p2KckpeZXNP5yjvvoJ
pGEPnOosw6iREPG35dyqLiVpvBiTBBwOVax7ZbD7hGEBWXrZWr/6cSq9AoGAY889
IxoPSHtbvJMOQSbjQ7wqX2J7I20gV5MXxyrxtwXgPEsPXNKZMAlUTmhthuq/oHA4
GUWHyCSUwBVcK3ut+ZIFCsKTX+oRyRSLhkbyGdsQ+2VuKbTKoK4KPhdUATFEdl+k
/gzyH9CCVJRxk6cmDihZdprm9TCb+HIw82BXSNECgYAc12DgeqlBWQgyUrFsgU7q
TBbZJHD6Mffdk1ci4hmmXiRemXI0gsLqBc/G0MGMpXgQZjZtCSO1p+lzWj4os2dV
h/BQWI19arRB+p437XcDaZmA+ywpXvPflSN2ujwTPck4Z1+fV1rE9XnOvP7gbom1
5wtxHwyU3T9JsKk2NVFZRQ==
-----END PRIVATE KEY-----"""
client_email = "kelvin@coherent-medium-474812-q4.iam.gserviceaccount.com"
client_id = "108183833330447577927"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/kelvin%40coherent-medium-474812-q4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
